apiVersion: v1
kind: Secret
metadata:
  name: pedidos-secrets
  namespace: pedidos-veloz
  labels:
    app: pedidos-veloz
    component: secrets
type: Opaque
data:
  # Valores em base64 (echo -n "valor" | base64)
  database.password: QWRtaW5AMTIz        # Admin@123
  redis.password: UmVkaXNAMTIzICAgICAg    # Redis@123
  rabbitmq.password: UmFiYml0QDEyMyAgICAg # Rabbit@123
  jwt.secret: SldUU2VjcmV0S2V5QDIwMjQ=  # JWTSecretKey@2024
